### PR TITLE
Fix install prefix containing Windows-style backslash path separator and catch JSON decode errors

### LINKED ISSUE #175: Install prefix paths with Windows-style backslash path separators cause several issues
Windows style paths with backslashes cause several issues -- in the worst case, a JSON decode error exception. In short, backslashes in strings get treated as escapes and gradually disappear as the install prefix gets used -- so if the install prefix contains a backslash, replace it with two backslashes so the resulting path will be `\\` instead of a single `\` that escapes the next character in some invalid way.

* `"installPrefix": "C:\abc"` -> results in JSON decode error exception
* `"installPrefix": "C:\\abc"` -> gives install paths such as `C:\u0007bc/lib64/libsomething.so` that incorrectly have the letter `a` escaped
* `"installPrefix": "C:\\\\abc"` -> gives install paths such as `C:\\abc/lib64/libsomething.so` which is correct... but not nice for the input config file installPrefix

### PR DESCRIPTION
**Pull request by nightlark**
Windows style paths with backslashes cause several issues -- in the worst case, a JSON decode error exception. This PR catches JSON decoding exceptions when reading from the config file and prints it with a slightly more user friendly message before exiting.

Other than that, backslashes get treated as escapes and gradually disappear as the install prefix gets used -- so if the install prefix contains a backslash, replace it with two backslashes so the resulting path will be `\\` instead of a single `\` that escapes the next character in some invalid way.

* `"installPrefix": "C:\abc"` -> results in JSON decode error exception
* `"installPrefix": "C:\\abc"` -> gives install paths such as `C:\u0007bc/lib64/libsomething.so` that incorrectly have the letter `a` escaped
* `"installPrefix": "C:\\\\abc"` -> gives install paths such as `C:\\abc/lib64/libsomething.so` which is correct... but not nice for the input config file installPrefix

Fixes #175

### CODE REVIEW

**Comment by nightlark** [comment]
To test this, use a Surfactant config file, and in the "installPrefix" field provide use some of the examples given above.

**Comment by mcutshaw** [comment]
I'm able to replicate the problem and while the solution helps, I need a little bit more time to understand some escaping issues between Python/JSON.

**Review by mcutshaw — APPROVED** [review]
On second thought I think I understand this well enough. While I'm not 100% sure that we want to adjust backslashes to fix unescaped characters in JSON this still seems reasonable enough.

**Comment by nightlark** [comment]
If you come up with some alternatives, we can continue refactoring this in future PRs -- it definitely feels a bit hacky, but it's not clear what the best way to stop Python from consuming '\`'s is.

**Pull request merged**
