### PR TITLE
Perf2

### PR DESCRIPTION
**Pull request by mcutshaw**
### Summary

If merged this pull request will improve performance and is discussed in #155 

### Proposed changes

See #155

### CODE REVIEW

**Comment by mcutshaw** [comment]
Please note I did disable pylints R0902, let me know if we want to change something as well. It would also appear I broke some of the unit tests, so I will need to fix those as well.

**Comment by mcutshaw** [comment]
@nightlark I believe this one is ready for review.

**Review by nightlark — APPROVED** [review]

**Review by nightlark — COMMENTED** [review]
Actually, one question -- does https://github.com/LLNL/Surfactant/blob/main/surfactant/cmd/merge.py for the merge subcommand need some changes to work with the sets (append -> add) and maintain the sha256 lookup table?

**Comment by mcutshaw** [comment]
> Actually, one question -- does https://github.com/LLNL/Surfactant/blob/main/surfactant/cmd/merge.py for the merge subcommand need some changes to work with the sets (append -> add) and maintain the sha256 lookup table?

Yes, I think there is only one change needed on line 61, but I will make sure and make edits tomorrow.

**Comment by nightlark** [comment]
I was thinking line 61, and two things in https://github.com/LLNL/Surfactant/blob/e2036bb62febeaa5c71913b2acac5fd5f2b6070f/surfactant/sbomtypes/_sbom.py#L120
- a call to relationships.append() in the merge function
- not updating the internal sha256 hashmap with software entries added via the merge function (if the entry to be added has a sha256 that isn’t None)
- the add_software function above the merge function in the SBOM class maybe should also update the hashmap (if the software entry has a sha256 hash)

I wonder if maybe the reason it didn’t break is that the merge function mostly uses the “internal” _ find functions that aren’t using the hashmap?

**Review by nightlark — APPROVED** [review]

**Comment by nightlark** [comment]
We might want to consider updating the [input reader for the cytrics format](https://github.com/LLNL/Surfactant/blob/main/surfactant/input_readers/cytrics_reader.py) to rebuild the sha256 hashmap when loading a new SBOM. I don't think this affects any of the functionality built-into Surfactant though, since reading existing SBOMs isn't used much (and where it is, the sha256 lookup table is not used).

**Pull request merged**
